[package]
name = "aoc2019"
version = "0.1.0"
authors = ["Sergey Kozub <sergey@kozub.email>"]
edition = "2018"

[dependencies]
itertools = "0.10.3"
libm = "0.1.3"
modinverse = "0.1.1"
num = "0.4.0"
regex = "1.5.4"
